/* 
 * Notifications API
 *
 * Notifications API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Telestream.Cloud.Notifications.Client.SwaggerDateConverter;

namespace Telestream.Cloud.Notifications.Model
{
    /// <summary>
    /// ModelParams
    /// </summary>
    [DataContract]
    public partial class ModelParams :  IEquatable<ModelParams>
    {
        /// <summary>
        /// #webhook  \&quot;HTTP method\&quot; 
        /// </summary>
        /// <value>#webhook  \&quot;HTTP method\&quot; </value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum MethodEnum
        {
            
            /// <summary>
            /// Enum Get for value: get
            /// </summary>
            [EnumMember(Value = "get")]
            Get = 1,
            
            /// <summary>
            /// Enum Post for value: post
            /// </summary>
            [EnumMember(Value = "post")]
            Post = 2
        }

        /// <summary>
        /// #webhook  \&quot;HTTP method\&quot; 
        /// </summary>
        /// <value>#webhook  \&quot;HTTP method\&quot; </value>
        [DataMember(Name="method", EmitDefaultValue=false)]
        public MethodEnum? Method { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ModelParams" /> class.
        /// </summary>
        /// <param name="Addresses">#email  E-mail address .</param>
        /// <param name="Url">#webhook  \&quot;Webhook URL\&quot; .</param>
        /// <param name="Method">#webhook  \&quot;HTTP method\&quot; .</param>
        /// <param name="Retries">#webhook  \&quot;Number of attempts before forgetting the notification\&quot; .</param>
        public ModelParams(List<string> Addresses = default(List<string>), string Url = default(string), MethodEnum? Method = default(MethodEnum?), int? Retries = default(int?))
        {
            this.Addresses = Addresses;
            this.Url = Url;
            this.Method = Method;
            this.Retries = Retries;
        }
        
        /// <summary>
        /// #email  E-mail address 
        /// </summary>
        /// <value>#email  E-mail address </value>
        [DataMember(Name="addresses", EmitDefaultValue=false)]
        public List<string> Addresses { get; set; }

        /// <summary>
        /// #webhook  \&quot;Webhook URL\&quot; 
        /// </summary>
        /// <value>#webhook  \&quot;Webhook URL\&quot; </value>
        [DataMember(Name="url", EmitDefaultValue=false)]
        public string Url { get; set; }


        /// <summary>
        /// #webhook  \&quot;Number of attempts before forgetting the notification\&quot; 
        /// </summary>
        /// <value>#webhook  \&quot;Number of attempts before forgetting the notification\&quot; </value>
        [DataMember(Name="retries", EmitDefaultValue=false)]
        public int? Retries { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ModelParams {\n");
            sb.Append("  Addresses: ").Append(Addresses).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Method: ").Append(Method).Append("\n");
            sb.Append("  Retries: ").Append(Retries).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ModelParams);
        }

        /// <summary>
        /// Returns true if ModelParams instances are equal
        /// </summary>
        /// <param name="input">Instance of ModelParams to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ModelParams input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Addresses == input.Addresses ||
                    this.Addresses != null &&
                    this.Addresses.SequenceEqual(input.Addresses)
                ) && 
                (
                    this.Url == input.Url ||
                    (this.Url != null &&
                    this.Url.Equals(input.Url))
                ) && 
                (
                    this.Method == input.Method ||
                    (this.Method != null &&
                    this.Method.Equals(input.Method))
                ) && 
                (
                    this.Retries == input.Retries ||
                    (this.Retries != null &&
                    this.Retries.Equals(input.Retries))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Addresses != null)
                    hashCode = hashCode * 59 + this.Addresses.GetHashCode();
                if (this.Url != null)
                    hashCode = hashCode * 59 + this.Url.GetHashCode();
                if (this.Method != null)
                    hashCode = hashCode * 59 + this.Method.GetHashCode();
                if (this.Retries != null)
                    hashCode = hashCode * 59 + this.Retries.GetHashCode();
                return hashCode;
            }
        }
    }

}
