/* 
 * Notifications API
 *
 * Notifications API V2
 *
 * OpenAPI spec version: 2.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Telestream.Cloud.Notifications.Api;
using Telestream.Cloud.Notifications.Model;
using Telestream.Cloud.Notifications.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Telestream.Cloud.Notifications.Test
{
    /// <summary>
    ///  Class for testing Topic
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TopicTests
    {
        // TODO uncomment below to declare an instance variable for Topic
        //private Topic instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Topic
            //instance = new Topic();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Topic
        /// </summary>
        [Test]
        public void TopicInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Topic
            //Assert.IsInstanceOfType<Topic> (instance, "variable 'instance' is a Topic");
        }


        /// <summary>
        /// Test the property 'Account'
        /// </summary>
        [Test]
        public void AccountTest()
        {
            // TODO unit test for the property 'Account'
        }
        /// <summary>
        /// Test the property 'Service'
        /// </summary>
        [Test]
        public void ServiceTest()
        {
            // TODO unit test for the property 'Service'
        }
        /// <summary>
        /// Test the property '_Event'
        /// </summary>
        [Test]
        public void _EventTest()
        {
            // TODO unit test for the property '_Event'
        }
        /// <summary>
        /// Test the property 'Project'
        /// </summary>
        [Test]
        public void ProjectTest()
        {
            // TODO unit test for the property 'Project'
        }
        /// <summary>
        /// Test the property 'Factory'
        /// </summary>
        [Test]
        public void FactoryTest()
        {
            // TODO unit test for the property 'Factory'
        }

    }

}
