/* 
 * Notifications API
 *
 * Notifications API V2
 *
 * OpenAPI spec version: 2.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Telestream.Cloud.Notifications.Api;
using Telestream.Cloud.Notifications.Model;
using Telestream.Cloud.Notifications.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Telestream.Cloud.Notifications.Test
{
    /// <summary>
    ///  Class for testing UpdateData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UpdateDataTests
    {
        // TODO uncomment below to declare an instance variable for UpdateData
        //private UpdateData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateData
            //instance = new UpdateData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateData
        /// </summary>
        [Test]
        public void UpdateDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdateData
            //Assert.IsInstanceOfType<UpdateData> (instance, "variable 'instance' is a UpdateData");
        }


        /// <summary>
        /// Test the property 'Topic'
        /// </summary>
        [Test]
        public void TopicTest()
        {
            // TODO unit test for the property 'Topic'
        }
        /// <summary>
        /// Test the property '_Params'
        /// </summary>
        [Test]
        public void _ParamsTest()
        {
            // TODO unit test for the property '_Params'
        }

    }

}
