/* 
 * API
 *
 * API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Telestream.Cloud.Stores.Client.SwaggerDateConverter;

namespace Telestream.Cloud.Stores.Model
{
    /// <summary>
    /// Store
    /// </summary>
    [DataContract]
    public partial class Store :  IEquatable<Store>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Store" /> class.
        /// </summary>
        /// <param name="Id">Id.</param>
        /// <param name="Name">Name.</param>
        /// <param name="Provider">Provider.</param>
        /// <param name="AccountId">AccountId.</param>
        /// <param name="BucketName">BucketName.</param>
        /// <param name="InputStore">InputStore.</param>
        /// <param name="WatchInterval">WatchInterval.</param>
        /// <param name="Region">Region.</param>
        /// <param name="PrivateAccess">PrivateAccess.</param>
        /// <param name="AccessKey">AccessKey.</param>
        /// <param name="SecretKey">SecretKey.</param>
        /// <param name="BaseUploadUrl">BaseUploadUrl.</param>
        /// <param name="ProviderSpecificSettings">ProviderSpecificSettings.</param>
        public Store(string Id = default(string), string Name = default(string), string Provider = default(string), string AccountId = default(string), string BucketName = default(string), bool? InputStore = default(bool?), int? WatchInterval = default(int?), string Region = default(string), bool? PrivateAccess = default(bool?), string AccessKey = default(string), string SecretKey = default(string), string BaseUploadUrl = default(string), StoreBodyProviderSpecificSettings ProviderSpecificSettings = default(StoreBodyProviderSpecificSettings))
        {
            this.Id = Id;
            this.Name = Name;
            this.Provider = Provider;
            this.AccountId = AccountId;
            this.BucketName = BucketName;
            this.InputStore = InputStore;
            this.WatchInterval = WatchInterval;
            this.Region = Region;
            this.PrivateAccess = PrivateAccess;
            this.AccessKey = AccessKey;
            this.SecretKey = SecretKey;
            this.BaseUploadUrl = BaseUploadUrl;
            this.ProviderSpecificSettings = ProviderSpecificSettings;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Provider
        /// </summary>
        [DataMember(Name="provider", EmitDefaultValue=false)]
        public string Provider { get; set; }

        /// <summary>
        /// Gets or Sets AccountId
        /// </summary>
        [DataMember(Name="account_id", EmitDefaultValue=false)]
        public string AccountId { get; set; }

        /// <summary>
        /// Gets or Sets BucketName
        /// </summary>
        [DataMember(Name="bucket_name", EmitDefaultValue=false)]
        public string BucketName { get; set; }

        /// <summary>
        /// Gets or Sets InputStore
        /// </summary>
        [DataMember(Name="input_store", EmitDefaultValue=false)]
        public bool? InputStore { get; set; }

        /// <summary>
        /// Gets or Sets WatchInterval
        /// </summary>
        [DataMember(Name="watch_interval", EmitDefaultValue=false)]
        public int? WatchInterval { get; set; }

        /// <summary>
        /// Gets or Sets Region
        /// </summary>
        [DataMember(Name="region", EmitDefaultValue=false)]
        public string Region { get; set; }

        /// <summary>
        /// Gets or Sets PrivateAccess
        /// </summary>
        [DataMember(Name="private_access", EmitDefaultValue=false)]
        public bool? PrivateAccess { get; set; }

        /// <summary>
        /// Gets or Sets AccessKey
        /// </summary>
        [DataMember(Name="access_key", EmitDefaultValue=false)]
        public string AccessKey { get; set; }

        /// <summary>
        /// Gets or Sets SecretKey
        /// </summary>
        [DataMember(Name="secret_key", EmitDefaultValue=false)]
        public string SecretKey { get; set; }

        /// <summary>
        /// Gets or Sets BaseUploadUrl
        /// </summary>
        [DataMember(Name="base_upload_url", EmitDefaultValue=false)]
        public string BaseUploadUrl { get; set; }

        /// <summary>
        /// Gets or Sets ProviderSpecificSettings
        /// </summary>
        [DataMember(Name="provider_specific_settings", EmitDefaultValue=false)]
        public StoreBodyProviderSpecificSettings ProviderSpecificSettings { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Store {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Provider: ").Append(Provider).Append("\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  BucketName: ").Append(BucketName).Append("\n");
            sb.Append("  InputStore: ").Append(InputStore).Append("\n");
            sb.Append("  WatchInterval: ").Append(WatchInterval).Append("\n");
            sb.Append("  Region: ").Append(Region).Append("\n");
            sb.Append("  PrivateAccess: ").Append(PrivateAccess).Append("\n");
            sb.Append("  AccessKey: ").Append(AccessKey).Append("\n");
            sb.Append("  SecretKey: ").Append(SecretKey).Append("\n");
            sb.Append("  BaseUploadUrl: ").Append(BaseUploadUrl).Append("\n");
            sb.Append("  ProviderSpecificSettings: ").Append(ProviderSpecificSettings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Store);
        }

        /// <summary>
        /// Returns true if Store instances are equal
        /// </summary>
        /// <param name="input">Instance of Store to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Store input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Provider == input.Provider ||
                    (this.Provider != null &&
                    this.Provider.Equals(input.Provider))
                ) && 
                (
                    this.AccountId == input.AccountId ||
                    (this.AccountId != null &&
                    this.AccountId.Equals(input.AccountId))
                ) && 
                (
                    this.BucketName == input.BucketName ||
                    (this.BucketName != null &&
                    this.BucketName.Equals(input.BucketName))
                ) && 
                (
                    this.InputStore == input.InputStore ||
                    (this.InputStore != null &&
                    this.InputStore.Equals(input.InputStore))
                ) && 
                (
                    this.WatchInterval == input.WatchInterval ||
                    (this.WatchInterval != null &&
                    this.WatchInterval.Equals(input.WatchInterval))
                ) && 
                (
                    this.Region == input.Region ||
                    (this.Region != null &&
                    this.Region.Equals(input.Region))
                ) && 
                (
                    this.PrivateAccess == input.PrivateAccess ||
                    (this.PrivateAccess != null &&
                    this.PrivateAccess.Equals(input.PrivateAccess))
                ) && 
                (
                    this.AccessKey == input.AccessKey ||
                    (this.AccessKey != null &&
                    this.AccessKey.Equals(input.AccessKey))
                ) && 
                (
                    this.SecretKey == input.SecretKey ||
                    (this.SecretKey != null &&
                    this.SecretKey.Equals(input.SecretKey))
                ) && 
                (
                    this.BaseUploadUrl == input.BaseUploadUrl ||
                    (this.BaseUploadUrl != null &&
                    this.BaseUploadUrl.Equals(input.BaseUploadUrl))
                ) && 
                (
                    this.ProviderSpecificSettings == input.ProviderSpecificSettings ||
                    (this.ProviderSpecificSettings != null &&
                    this.ProviderSpecificSettings.Equals(input.ProviderSpecificSettings))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Provider != null)
                    hashCode = hashCode * 59 + this.Provider.GetHashCode();
                if (this.AccountId != null)
                    hashCode = hashCode * 59 + this.AccountId.GetHashCode();
                if (this.BucketName != null)
                    hashCode = hashCode * 59 + this.BucketName.GetHashCode();
                if (this.InputStore != null)
                    hashCode = hashCode * 59 + this.InputStore.GetHashCode();
                if (this.WatchInterval != null)
                    hashCode = hashCode * 59 + this.WatchInterval.GetHashCode();
                if (this.Region != null)
                    hashCode = hashCode * 59 + this.Region.GetHashCode();
                if (this.PrivateAccess != null)
                    hashCode = hashCode * 59 + this.PrivateAccess.GetHashCode();
                if (this.AccessKey != null)
                    hashCode = hashCode * 59 + this.AccessKey.GetHashCode();
                if (this.SecretKey != null)
                    hashCode = hashCode * 59 + this.SecretKey.GetHashCode();
                if (this.BaseUploadUrl != null)
                    hashCode = hashCode * 59 + this.BaseUploadUrl.GetHashCode();
                if (this.ProviderSpecificSettings != null)
                    hashCode = hashCode * 59 + this.ProviderSpecificSettings.GetHashCode();
                return hashCode;
            }
        }
    }

}
