/* 
 * Flip API
 *
 * Description
 *
 * OpenAPI spec version: 2.0.1
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Telestream.Cloud.Flip.Api;
using Telestream.Cloud.Flip.Model;
using Telestream.Cloud.Flip.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Telestream.Cloud.Flip.Test
{
    /// <summary>
    ///  Class for testing CopyProfileBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CopyProfileBodyTests
    {
        // TODO uncomment below to declare an instance variable for CopyProfileBody
        //private CopyProfileBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CopyProfileBody
            //instance = new CopyProfileBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CopyProfileBody
        /// </summary>
        [Test]
        public void CopyProfileBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CopyProfileBody
            //Assert.IsInstanceOfType<CopyProfileBody> (instance, "variable 'instance' is a CopyProfileBody");
        }


        /// <summary>
        /// Test the property 'DestFactoryId'
        /// </summary>
        [Test]
        public void DestFactoryIdTest()
        {
            // TODO unit test for the property 'DestFactoryId'
        }
        /// <summary>
        /// Test the property 'ProfileName'
        /// </summary>
        [Test]
        public void ProfileNameTest()
        {
            // TODO unit test for the property 'ProfileName'
        }

    }

}
