/* 
 * Flip API
 *
 * Description
 *
 * OpenAPI spec version: 2.0.1
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Telestream.Cloud.Flip.Api;
using Telestream.Cloud.Flip.Model;
using Telestream.Cloud.Flip.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Telestream.Cloud.Flip.Test
{
    /// <summary>
    ///  Class for testing EncodingSignedUrls
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EncodingSignedUrlsTests
    {
        // TODO uncomment below to declare an instance variable for EncodingSignedUrls
        //private EncodingSignedUrls instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EncodingSignedUrls
            //instance = new EncodingSignedUrls();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EncodingSignedUrls
        /// </summary>
        [Test]
        public void EncodingSignedUrlsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EncodingSignedUrls
            //Assert.IsInstanceOfType<EncodingSignedUrls> (instance, "variable 'instance' is a EncodingSignedUrls");
        }


        /// <summary>
        /// Test the property 'SignedUrls'
        /// </summary>
        [Test]
        public void SignedUrlsTest()
        {
            // TODO unit test for the property 'SignedUrls'
        }

    }

}
