/* 
 * Flip API
 *
 * Description
 *
 * OpenAPI spec version: 2.0.1
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Telestream.Cloud.Flip.Api;
using Telestream.Cloud.Flip.Model;
using Telestream.Cloud.Flip.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Telestream.Cloud.Flip.Test
{
    /// <summary>
    ///  Class for testing Factory
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FactoryTests
    {
        // TODO uncomment below to declare an instance variable for Factory
        //private Factory instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Factory
            //instance = new Factory();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Factory
        /// </summary>
        [Test]
        public void FactoryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Factory
            //Assert.IsInstanceOfType<Factory> (instance, "variable 'instance' is a Factory");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'ServerSideEncryption'
        /// </summary>
        [Test]
        public void ServerSideEncryptionTest()
        {
            // TODO unit test for the property 'ServerSideEncryption'
        }
        /// <summary>
        /// Test the property 'OutputsPathFormat'
        /// </summary>
        [Test]
        public void OutputsPathFormatTest()
        {
            // TODO unit test for the property 'OutputsPathFormat'
        }
        /// <summary>
        /// Test the property 'StoreId'
        /// </summary>
        [Test]
        public void StoreIdTest()
        {
            // TODO unit test for the property 'StoreId'
        }

    }

}
