/* 
 * Flip API
 *
 * Description
 *
 * OpenAPI spec version: 2.0.1
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Telestream.Cloud.Flip.Api;
using Telestream.Cloud.Flip.Model;
using Telestream.Cloud.Flip.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Telestream.Cloud.Flip.Test
{
    /// <summary>
    ///  Class for testing PaginatedFactoryCollection
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PaginatedFactoryCollectionTests
    {
        // TODO uncomment below to declare an instance variable for PaginatedFactoryCollection
        //private PaginatedFactoryCollection instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PaginatedFactoryCollection
            //instance = new PaginatedFactoryCollection();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PaginatedFactoryCollection
        /// </summary>
        [Test]
        public void PaginatedFactoryCollectionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PaginatedFactoryCollection
            //Assert.IsInstanceOfType<PaginatedFactoryCollection> (instance, "variable 'instance' is a PaginatedFactoryCollection");
        }


        /// <summary>
        /// Test the property 'Factories'
        /// </summary>
        [Test]
        public void FactoriesTest()
        {
            // TODO unit test for the property 'Factories'
        }
        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Test]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }
        /// <summary>
        /// Test the property 'PerPage'
        /// </summary>
        [Test]
        public void PerPageTest()
        {
            // TODO unit test for the property 'PerPage'
        }
        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Test]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }

    }

}
