/* 
 * Flip API
 *
 * Description
 *
 * OpenAPI spec version: 2.0.1
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Telestream.Cloud.Flip.Api;
using Telestream.Cloud.Flip.Model;
using Telestream.Cloud.Flip.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Telestream.Cloud.Flip.Test
{
    /// <summary>
    ///  Class for testing ResubmitVideoBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ResubmitVideoBodyTests
    {
        // TODO uncomment below to declare an instance variable for ResubmitVideoBody
        //private ResubmitVideoBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ResubmitVideoBody
            //instance = new ResubmitVideoBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ResubmitVideoBody
        /// </summary>
        [Test]
        public void ResubmitVideoBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ResubmitVideoBody
            //Assert.IsInstanceOfType<ResubmitVideoBody> (instance, "variable 'instance' is a ResubmitVideoBody");
        }


        /// <summary>
        /// Test the property 'VideoId'
        /// </summary>
        [Test]
        public void VideoIdTest()
        {
            // TODO unit test for the property 'VideoId'
        }

    }

}
