/* 
 * Flip API
 *
 * Description
 *
 * OpenAPI spec version: 2.0.1
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Telestream.Cloud.Flip.Api;
using Telestream.Cloud.Flip.Model;
using Telestream.Cloud.Flip.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Telestream.Cloud.Flip.Test
{
    /// <summary>
    ///  Class for testing RetriedResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RetriedResponseTests
    {
        // TODO uncomment below to declare an instance variable for RetriedResponse
        //private RetriedResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RetriedResponse
            //instance = new RetriedResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RetriedResponse
        /// </summary>
        [Test]
        public void RetriedResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RetriedResponse
            //Assert.IsInstanceOfType<RetriedResponse> (instance, "variable 'instance' is a RetriedResponse");
        }


        /// <summary>
        /// Test the property 'Retried'
        /// </summary>
        [Test]
        public void RetriedTest()
        {
            // TODO unit test for the property 'Retried'
        }

    }

}
