/* 
 * API
 *
 * API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Telestream.Cloud.Stores.Api;
using Telestream.Cloud.Stores.Model;
using Telestream.Cloud.Stores.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Telestream.Cloud.Stores.Test
{
    /// <summary>
    ///  Class for testing ObjectURL
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ObjectURLTests
    {
        // TODO uncomment below to declare an instance variable for ObjectURL
        //private ObjectURL instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ObjectURL
            //instance = new ObjectURL();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ObjectURL
        /// </summary>
        [Test]
        public void ObjectURLInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ObjectURL
            //Assert.IsInstanceOfType<ObjectURL> (instance, "variable 'instance' is a ObjectURL");
        }


        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

    }

}
