/* 
 * API
 *
 * API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Telestream.Cloud.Stores.Api;
using Telestream.Cloud.Stores.Model;
using Telestream.Cloud.Stores.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Telestream.Cloud.Stores.Test
{
    /// <summary>
    ///  Class for testing Output
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OutputTests
    {
        // TODO uncomment below to declare an instance variable for Output
        //private Output instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Output
            //instance = new Output();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Output
        /// </summary>
        [Test]
        public void OutputInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Output
            //Assert.IsInstanceOfType<Output> (instance, "variable 'instance' is a Output");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'PathFormat'
        /// </summary>
        [Test]
        public void PathFormatTest()
        {
            // TODO unit test for the property 'PathFormat'
        }
        /// <summary>
        /// Test the property 'StoreId'
        /// </summary>
        [Test]
        public void StoreIdTest()
        {
            // TODO unit test for the property 'StoreId'
        }
        /// <summary>
        /// Test the property 'ServiceId'
        /// </summary>
        [Test]
        public void ServiceIdTest()
        {
            // TODO unit test for the property 'ServiceId'
        }
        /// <summary>
        /// Test the property 'ServiceName'
        /// </summary>
        [Test]
        public void ServiceNameTest()
        {
            // TODO unit test for the property 'ServiceName'
        }

    }

}
