/* 
 * API
 *
 * API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Telestream.Cloud.Stores.Api;
using Telestream.Cloud.Stores.Model;
using Telestream.Cloud.Stores.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Telestream.Cloud.Stores.Test
{
    /// <summary>
    ///  Class for testing Store
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StoreTests
    {
        // TODO uncomment below to declare an instance variable for Store
        //private Store instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Store
            //instance = new Store();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Store
        /// </summary>
        [Test]
        public void StoreInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Store
            //Assert.IsInstanceOfType<Store> (instance, "variable 'instance' is a Store");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Provider'
        /// </summary>
        [Test]
        public void ProviderTest()
        {
            // TODO unit test for the property 'Provider'
        }
        /// <summary>
        /// Test the property 'BucketName'
        /// </summary>
        [Test]
        public void BucketNameTest()
        {
            // TODO unit test for the property 'BucketName'
        }
        /// <summary>
        /// Test the property 'InputStore'
        /// </summary>
        [Test]
        public void InputStoreTest()
        {
            // TODO unit test for the property 'InputStore'
        }
        /// <summary>
        /// Test the property 'WatchInterval'
        /// </summary>
        [Test]
        public void WatchIntervalTest()
        {
            // TODO unit test for the property 'WatchInterval'
        }
        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Test]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }
        /// <summary>
        /// Test the property 'PrivateAccess'
        /// </summary>
        [Test]
        public void PrivateAccessTest()
        {
            // TODO unit test for the property 'PrivateAccess'
        }
        /// <summary>
        /// Test the property 'AccessKey'
        /// </summary>
        [Test]
        public void AccessKeyTest()
        {
            // TODO unit test for the property 'AccessKey'
        }
        /// <summary>
        /// Test the property 'SecretKey'
        /// </summary>
        [Test]
        public void SecretKeyTest()
        {
            // TODO unit test for the property 'SecretKey'
        }
        /// <summary>
        /// Test the property 'ProviderSpecificSettings'
        /// </summary>
        [Test]
        public void ProviderSpecificSettingsTest()
        {
            // TODO unit test for the property 'ProviderSpecificSettings'
        }

    }

}
