/* 
 * API
 *
 * API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Telestream.Cloud.Stores.Api;
using Telestream.Cloud.Stores.Model;
using Telestream.Cloud.Stores.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Telestream.Cloud.Stores.Test
{
    /// <summary>
    ///  Class for testing ValidateBucketBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ValidateBucketBodyTests
    {
        // TODO uncomment below to declare an instance variable for ValidateBucketBody
        //private ValidateBucketBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ValidateBucketBody
            //instance = new ValidateBucketBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ValidateBucketBody
        /// </summary>
        [Test]
        public void ValidateBucketBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ValidateBucketBody
            //Assert.IsInstanceOfType<ValidateBucketBody> (instance, "variable 'instance' is a ValidateBucketBody");
        }


        /// <summary>
        /// Test the property 'BucketName'
        /// </summary>
        [Test]
        public void BucketNameTest()
        {
            // TODO unit test for the property 'BucketName'
        }
        /// <summary>
        /// Test the property 'Provider'
        /// </summary>
        [Test]
        public void ProviderTest()
        {
            // TODO unit test for the property 'Provider'
        }
        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Test]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }
        /// <summary>
        /// Test the property 'AccessKey'
        /// </summary>
        [Test]
        public void AccessKeyTest()
        {
            // TODO unit test for the property 'AccessKey'
        }
        /// <summary>
        /// Test the property 'SecretKey'
        /// </summary>
        [Test]
        public void SecretKeyTest()
        {
            // TODO unit test for the property 'SecretKey'
        }

    }

}
