/* 
 * Tts API
 *
 * Description
 *
 * OpenAPI spec version: 2.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Telestream.Cloud.Tts.Api;
using Telestream.Cloud.Tts.Model;
using Telestream.Cloud.Tts.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Telestream.Cloud.Tts.Test
{
    /// <summary>
    ///  Class for testing Corpus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CorpusTests
    {
        // TODO uncomment below to declare an instance variable for Corpus
        //private Corpus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Corpus
            //instance = new Corpus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Corpus
        /// </summary>
        [Test]
        public void CorpusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Corpus
            //Assert.IsInstanceOfType<Corpus> (instance, "variable 'instance' is a Corpus");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
