/* 
 * Tts API
 *
 * Description
 *
 * OpenAPI spec version: 2.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Telestream.Cloud.Tts.Api;
using Telestream.Cloud.Tts.Model;
using Telestream.Cloud.Tts.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Telestream.Cloud.Tts.Test
{
    /// <summary>
    ///  Class for testing CorporaCollection
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CorporaCollectionTests
    {
        // TODO uncomment below to declare an instance variable for CorporaCollection
        //private CorporaCollection instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CorporaCollection
            //instance = new CorporaCollection();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CorporaCollection
        /// </summary>
        [Test]
        public void CorporaCollectionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CorporaCollection
            //Assert.IsInstanceOfType<CorporaCollection> (instance, "variable 'instance' is a CorporaCollection");
        }


        /// <summary>
        /// Test the property 'Corpora'
        /// </summary>
        [Test]
        public void CorporaTest()
        {
            // TODO unit test for the property 'Corpora'
        }

    }

}
