/* 
 * Tts API
 *
 * Description
 *
 * OpenAPI spec version: 2.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Telestream.Cloud.Tts.Api;
using Telestream.Cloud.Tts.Model;
using Telestream.Cloud.Tts.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Telestream.Cloud.Tts.Test
{
    /// <summary>
    ///  Class for testing JobsCollection
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class JobsCollectionTests
    {
        // TODO uncomment below to declare an instance variable for JobsCollection
        //private JobsCollection instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of JobsCollection
            //instance = new JobsCollection();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of JobsCollection
        /// </summary>
        [Test]
        public void JobsCollectionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" JobsCollection
            //Assert.IsInstanceOfType<JobsCollection> (instance, "variable 'instance' is a JobsCollection");
        }


        /// <summary>
        /// Test the property 'Jobs'
        /// </summary>
        [Test]
        public void JobsTest()
        {
            // TODO unit test for the property 'Jobs'
        }
        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Test]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }
        /// <summary>
        /// Test the property 'PerPage'
        /// </summary>
        [Test]
        public void PerPageTest()
        {
            // TODO unit test for the property 'PerPage'
        }
        /// <summary>
        /// Test the property 'PageCount'
        /// </summary>
        [Test]
        public void PageCountTest()
        {
            // TODO unit test for the property 'PageCount'
        }
        /// <summary>
        /// Test the property 'TotalCount'
        /// </summary>
        [Test]
        public void TotalCountTest()
        {
            // TODO unit test for the property 'TotalCount'
        }

    }

}
