/* 
 * Tts API
 *
 * Description
 *
 * OpenAPI spec version: 2.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Telestream.Cloud.Tts.Api;
using Telestream.Cloud.Tts.Model;
using Telestream.Cloud.Tts.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Telestream.Cloud.Tts.Test
{
    /// <summary>
    ///  Class for testing Job
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class JobTests
    {
        // TODO uncomment below to declare an instance variable for Job
        //private Job instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Job
            //instance = new Job();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Job
        /// </summary>
        [Test]
        public void JobInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Job
            //Assert.IsInstanceOfType<Job> (instance, "variable 'instance' is a Job");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'OriginalFilename'
        /// </summary>
        [Test]
        public void OriginalFilenameTest()
        {
            // TODO unit test for the property 'OriginalFilename'
        }
        /// <summary>
        /// Test the property 'ProjectId'
        /// </summary>
        [Test]
        public void ProjectIdTest()
        {
            // TODO unit test for the property 'ProjectId'
        }
        /// <summary>
        /// Test the property 'SourceUrl'
        /// </summary>
        [Test]
        public void SourceUrlTest()
        {
            // TODO unit test for the property 'SourceUrl'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Test]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
        /// <summary>
        /// Test the property 'Progress'
        /// </summary>
        [Test]
        public void ProgressTest()
        {
            // TODO unit test for the property 'Progress'
        }
        /// <summary>
        /// Test the property 'Confidence'
        /// </summary>
        [Test]
        public void ConfidenceTest()
        {
            // TODO unit test for the property 'Confidence'
        }
        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Test]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }
        /// <summary>
        /// Test the property 'Bitrate'
        /// </summary>
        [Test]
        public void BitrateTest()
        {
            // TODO unit test for the property 'Bitrate'
        }
        /// <summary>
        /// Test the property 'SampleRate'
        /// </summary>
        [Test]
        public void SampleRateTest()
        {
            // TODO unit test for the property 'SampleRate'
        }
        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Test]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }
        /// <summary>
        /// Test the property 'FileSize'
        /// </summary>
        [Test]
        public void FileSizeTest()
        {
            // TODO unit test for the property 'FileSize'
        }
        /// <summary>
        /// Test the property 'CustomWords'
        /// </summary>
        [Test]
        public void CustomWordsTest()
        {
            // TODO unit test for the property 'CustomWords'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

    }

}
