/* 
 * Tts API
 *
 * Description
 *
 * OpenAPI spec version: 2.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Telestream.Cloud.Tts.Api;
using Telestream.Cloud.Tts.Model;
using Telestream.Cloud.Tts.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Telestream.Cloud.Tts.Test
{
    /// <summary>
    ///  Class for testing Project
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProjectTests
    {
        // TODO uncomment below to declare an instance variable for Project
        //private Project instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Project
            //instance = new Project();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Project
        /// </summary>
        [Test]
        public void ProjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Project
            //Assert.IsInstanceOfType<Project> (instance, "variable 'instance' is a Project");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Test]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'SampleRate'
        /// </summary>
        [Test]
        public void SampleRateTest()
        {
            // TODO unit test for the property 'SampleRate'
        }
        /// <summary>
        /// Test the property 'ProfanityFilter'
        /// </summary>
        [Test]
        public void ProfanityFilterTest()
        {
            // TODO unit test for the property 'ProfanityFilter'
        }
        /// <summary>
        /// Test the property 'GenerateProxy'
        /// </summary>
        [Test]
        public void GenerateProxyTest()
        {
            // TODO unit test for the property 'GenerateProxy'
        }
        /// <summary>
        /// Test the property 'CustomWords'
        /// </summary>
        [Test]
        public void CustomWordsTest()
        {
            // TODO unit test for the property 'CustomWords'
        }
        /// <summary>
        /// Test the property 'Capabilities'
        /// </summary>
        [Test]
        public void CapabilitiesTest()
        {
            // TODO unit test for the property 'Capabilities'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

    }

}
