/* 
 * IAM API
 *
 * IAM API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Telestream.Cloud.Iam.Api;
using Telestream.Cloud.Iam.Model;
using Telestream.Cloud.Iam.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Telestream.Cloud.Iam.Test
{
    /// <summary>
    ///  Class for testing StatementsList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StatementsListTests
    {
        // TODO uncomment below to declare an instance variable for StatementsList
        //private StatementsList instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StatementsList
            //instance = new StatementsList();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StatementsList
        /// </summary>
        [Test]
        public void StatementsListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StatementsList
            //Assert.IsInstanceOfType<StatementsList> (instance, "variable 'instance' is a StatementsList");
        }


        /// <summary>
        /// Test the property 'Statements'
        /// </summary>
        [Test]
        public void StatementsTest()
        {
            // TODO unit test for the property 'Statements'
        }

    }

}
