/* 
 * Flip API
 *
 * Description
 *
 * OpenAPI spec version: 2.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Telestream.Cloud.Flip.Client.SwaggerDateConverter;

namespace Telestream.Cloud.Flip.Model
{
    /// <summary>
    /// EncodingSignedUrls
    /// </summary>
    [DataContract]
    public partial class EncodingSignedUrls :  IEquatable<EncodingSignedUrls>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EncodingSignedUrls" /> class.
        /// </summary>
        /// <param name="SignedUrls">A list of signed URLs pointing to the encoding&#39;s outputs..</param>
        public EncodingSignedUrls(List<string> SignedUrls = default(List<string>))
        {
            this.SignedUrls = SignedUrls;
        }
        
        /// <summary>
        /// A list of signed URLs pointing to the encoding&#39;s outputs.
        /// </summary>
        /// <value>A list of signed URLs pointing to the encoding&#39;s outputs.</value>
        [DataMember(Name="signed_urls", EmitDefaultValue=false)]
        public List<string> SignedUrls { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EncodingSignedUrls {\n");
            sb.Append("  SignedUrls: ").Append(SignedUrls).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EncodingSignedUrls);
        }

        /// <summary>
        /// Returns true if EncodingSignedUrls instances are equal
        /// </summary>
        /// <param name="input">Instance of EncodingSignedUrls to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EncodingSignedUrls input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SignedUrls == input.SignedUrls ||
                    this.SignedUrls != null &&
                    this.SignedUrls.SequenceEqual(input.SignedUrls)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SignedUrls != null)
                    hashCode = hashCode * 59 + this.SignedUrls.GetHashCode();
                return hashCode;
            }
        }
    }

}
