/* 
 * Flip API
 *
 * Description
 *
 * OpenAPI spec version: 3.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Telestream.Cloud.Flip.Client.SwaggerDateConverter;

namespace Telestream.Cloud.Flip.Model
{
    /// <summary>
    /// ResubmitVideoBody
    /// </summary>
    [DataContract]
    public partial class ResubmitVideoBody :  IEquatable<ResubmitVideoBody>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResubmitVideoBody" /> class.
        /// </summary>
        /// <param name="VideoId">Id of the video..</param>
        public ResubmitVideoBody(string VideoId = default(string))
        {
            this.VideoId = VideoId;
        }
        
        /// <summary>
        /// Id of the video.
        /// </summary>
        /// <value>Id of the video.</value>
        [DataMember(Name="video_id", EmitDefaultValue=false)]
        public string VideoId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ResubmitVideoBody {\n");
            sb.Append("  VideoId: ").Append(VideoId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ResubmitVideoBody);
        }

        /// <summary>
        /// Returns true if ResubmitVideoBody instances are equal
        /// </summary>
        /// <param name="input">Instance of ResubmitVideoBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ResubmitVideoBody input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.VideoId == input.VideoId ||
                    (this.VideoId != null &&
                    this.VideoId.Equals(input.VideoId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.VideoId != null)
                    hashCode = hashCode * 59 + this.VideoId.GetHashCode();
                return hashCode;
            }
        }
    }

}
